name: ONC Patient Engagement Playbook
description: ONC Patient Engagement Playbook
url: //healthit.gov
baseurl: "/playbook/pe"

port: 4000
host: 127.0.0.1

sass:
  sass_dir: _sass
  style: :compressed

lsi: false
markdown: kramdown
source: .
destination: _site
permalink: /:categories/:title/
timezone: America/New_York

feed:
  path: feed.xml

exclude: [node_modules, '.sass-cache', Gemfile, Gemfile.lock, README.md, package.json, Gruntfile.js, _content/styleguide.html, _content/styleguide-grammar.html]

collections:
  content:
    output: true
